# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#站点基础配置
title: Cocoa520
subTitle: 千里之行，始于足下。
description: 这是一个基于 Jekyll 搭建起来的博客。在这里，我将用来记录工作，学习，生活中的一点一滴，同时也是对 Jekyll 的学习和使用的一次有意义的实践。
url: http://cocoa520.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 翻译转载
    url: /archives.html
  - text: 项目
    url: /404.html
  - text: 关于
    url: /contact.html
  - text: Objc123
    url: http://www.objc123.com

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: http://www.cocoa520.com
  - class: fa-facebook
    url: http://www.cocoa520.com
  - class: fa-github
    url: http://github.com/cocoa520
  - class: fa-weibo
    url: http://weibo.com/1643331874
  - class: fa-renren
    url: http://www.cocoa520.com
  - class: fa-pinterest
    url: http://www.cocoa520.com
  - class: fa-twitter
    url: http://www.cocoa520.com
  - class: fa-rss
    url: http://www.cocoa520.com

#作者信息
author:
  link: http://www.cocoa520.com/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
disqus:
  config: true
  id: cocoa520

duoshuo:
  config: false
  id: cocoa520